### ISSUE TITLE
Only the first table link (button) is generated

### ISSUE THREAD

**Issue by steveshead** [jan-vandenberg/cruddiy#1]
All files are being generated for all tables correctly but, once the generation process is complete only one link (button) is created and displayed on the index page, and that seems to be for the first table only.  There is an easy workaround - but - wanted to see if there is a way to fix that.

**Comment by jan-vandenberg** [comment]
You're right! 
Fixed: https://github.com/jan-vandenberg/cruddiy/commit/9ef2fa0c73ff2260b2867d26afd544a0f0ad59f3

Thanks!
