### ISSUE TITLE
Question: Choose from list/dropdown when adding a new record

### ISSUE THREAD

**Issue by michielsebastiaan** [jan-vandenberg/cruddiy#137]
Hello,

Just recently found this awesome lifesaver. 
I have a small question.

I have created a MySQL database and set op some tables. 
One or more tables have fields with the "SET" Type.
Assuming this would give me a dropdown list when adding a new record. 
How would I achieve this? 

![image](https://github.com/jan-vandenberg/cruddiy/assets/167966541/1366f291-80e2-43da-b5e9-3cdaeac385da)

 Thanks in advance,
 Michiel

**Comment by germain-italic** [comment]
Hi Michiel,
[ENUM is supported in Cruddiy](https://github.com/jan-vandenberg/cruddiy/blob/890e743cd0041e9652b12714d746e988d8adf624/core/generate.php#L867)

Could you try by changing your datatype to ENUM instead of SET?
This should achieve the same result.

**Comment by michielsebastiaan** [comment]
Thank you for the swift answer. 
Yes, it works now.  Like a charm.
Case solved
