### ISSUE TITLE
cannot install "Unable to open file!"

### ISSUE THREAD

**Issue by VanDerLars** [jan-vandenberg/cruddiy#15]
Hi,
I tried cruddiy. Uploaded it, entered all credentials and after clicking "Submit" only the following message is shown: 
"Unable to open file!".

In the error is nothing suspicious.

Can you help?

**Comment by jan-vandenberg** [comment]
My guess is your file permissions are wrong. 
Make sure you chown the entire Cruddiy dir to the same user you run your webserver under (e.g.  chown www-data.www-data cruddiy-master -R)

**Comment by VanDerLars** [comment]
Worked! Thanks!
