### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by maxresnikoff** [jan-vandenberg/cruddiy#25]
When you filter by a column (eg. name) and click next page, it removes the filtering completely from the URL and just shows: pageno=2

**Comment by jan-vandenberg** [comment]
Interesting! That might be fixable, I'll have to look at it.

**Comment by jan-vandenberg** [comment]
I just tested this on the latest Cruddiy code, but this seems to work fine?

The URL looks like this (the column is Name):
?search=&sort=&order=Name&sort=desc&pageno=3

**Comment by maxresnikoff** [comment]
Strange... 
Mine goes from this: **?search=&sort=&order=airport_ident&sort=desc**
To this: **?pageno=2**

I only just installed the v1.0 release so its a fresh copy of cruddiy

**Comment by jan-vandenberg** [comment]
O wow, that explains it, the code for 1.0 is really old! You should really pull in the latest code! 

I just created a new release with lots of fixes (and the latest code): https://github.com/jan-vandenberg/cruddiy/releases/tag/v2.0

**Comment by maxresnikoff** [comment]
ha! that was it! thanks 😅
