### ISSUE TITLE
Searching doesnt seem to work?

### ISSUE THREAD

**Issue by maxresnikoff** [jan-vandenberg/cruddiy#26]
When I type anything (which I know exists as is in the table below the search bar) it returns **No records were found.**

This only happens on 1 table for some reason

**Comment by jan-vandenberg** [comment]
Can you share the table structure maybe?

**Comment by maxresnikoff** [comment]
Of course!

`-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: May 06, 2021 at 11:36 AM
-- Server version: 5.7.32-35-log
-- PHP Version: 7.3.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_tools`
--

-- --------------------------------------------------------

--
-- Table structure for table `data_airlines`
--

CREATE TABLE `data_airlines` (
  `id` int(11) NOT NULL,
  `name` varchar(81) NOT NULL,
  `alias` varchar(30) DEFAULT NULL,
  `iata` varchar(3) DEFAULT NULL,
  `icao` varchar(5) DEFAULT NULL,
  `callsign` varchar(50) DEFAULT NULL,
  `country` varchar(37) DEFAULT NULL,
  `active` varchar(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `data_airlines`
--
ALTER TABLE `data_airlines`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
`

**Comment by maxresnikoff** [comment]
I have echoed out the SQL statement and pasted it into phpmyadmin.

If I remove the CONCAT(), and just leave the 'name' column, it works. it returns all.

**Comment by maxresnikoff** [comment]
I can confirm that using CONCAT_WS instead of CONCAT does work. 
Not sure if this conflict or causes any issues with other parts of your awesome CRUD framework, but would be nice if it could be updated so I don't have to edit each index.php file each time I update to the latest version, or regenerate all CRUDs
