### ISSUE TITLE
When generating pages, 'Visible name' only applying to first item

### ISSUE THREAD

**Issue by maxresnikoff** [jan-vandenberg/cruddiy#28]
This might be me being thick again, but when you add a visible name to all the selected tables, It only applies the change to the first button (eg, I change them to this):
- Airports, 
- Airlines
- Runwayws
- etc

And when it is all generated, it shows the actual table name except for the first button

![image](https://user-images.githubusercontent.com/48560713/117303465-9e49ad00-ae74-11eb-9e8f-a48e1fdbb509.png)

**Comment by jan-vandenberg** [comment]
Thanks for pointing this out! I'll have a look at it.

**Comment by jan-vandenberg** [comment]
This was broken because of a recent PR. 
This is fixed in the latest push: https://github.com/jan-vandenberg/cruddiy/commit/f8655699b9e42ff5d093b92cc80570300fd5be38
