### ISSUE TITLE
Problem with foreign keys

### ISSUE THREAD

**Issue by franMx** [jan-vandenberg/cruddiy#35]
Hi, trying to generate a crud from some tables that have already set a relation in phpmyadmin. The key is shown, not the actual 'name' set in table. Can cruddiy automagically generate those? Thanks.

**Comment by jan-vandenberg** [comment]
Interesting can you share a screenshot or maybe the database schema?

**Comment by franMx** [comment]
Sure, here goes the sql
[pleaseCheck.zip](https://github.com/jan-vandenberg/cruddiy/files/6748676/pleaseCheck.zip)

**Comment by franMx** [comment]
The  I missunderstood the function then. Was expecting to see actual deparment anme instead of index, for example. 
![Capture](https://user-images.githubusercontent.com/8523314/124138437-42eb0400-da4c-11eb-9ea7-d5ad77175510.PNG)

**Comment by jan-vandenberg** [comment]
Ah right, that is still a missing feature. I haven't had time to work on this yet.
Also see https://github.com/jan-vandenberg/cruddiy/issues/14

**Comment by franMx** [comment]
Got it! Thanks.
