### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [jan-vandenberg/cruddiy#38]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jan-vandenberg** [comment]
Hi you can reach me at janvdberg at gmail dot com. I'll look into adding a SECURITY.md file (you can also reach me at cruddiy.com).

**Comment by jan-vandenberg** [comment]
I will not be adding a SECURITY.md  for two reasons:

1. The whole idea is that you delete Cruddiy when it's finished. The generated app is what you want.
2. When there are security issues within the generated app, people would need to contact the app owner and not me. So having my e-mail address in the SECURITY.md file would maybe send people in the wrong direction.
