### ISSUE TITLE
Sorting is not keep with pagination

### ISSUE THREAD

**Issue by eried** [jan-vandenberg/cruddiy#4]
Another small bug is that if you sort clicking the header of the table, and switch to another page, the sorting is lost. So it is quite difficult to use pagination in any way.

**Comment by jan-vandenberg** [comment]
Nice find! Thanks. Fixed here: https://github.com/jan-vandenberg/cruddiy/commit/80a2d1c60c3f70e720d9d472b46e95a5075c550f
