### ISSUE TITLE
Easy fix to search parameter not being passed along in URL when paging

### ISSUE THREAD

**Issue by dooleysworne** [jan-vandenberg/cruddiy#45]
Line 54 in templates.php

Change 

$parameters   = **$GET** ? $_SERVER['QUERY_STRING'] : "" ;

to

$parameters   = **$_GET** ? $_SERVER['QUERY_STRING'] : "" ;

Solves the problem of the search parameter not being passed along in the URL when paging.

**Comment by jan-vandenberg** [comment]
What version of Cruddiy are you using (or which git commit)? Because this line is not in the code.

See here: https://github.com/jan-vandenberg/cruddiy/blob/master/core/templates.php#L54

**Comment by dooleysworne** [comment]
???
In https://github.com/jan-vandenberg/cruddiy/blob/master/core/templates.php#L54, $GET needs to be changed to $_GET

**Comment by jan-vandenberg** [comment]
Wow, I did not catch this because my development branch wasn't synced with master (which was ahead). 

Fixed now in https://github.com/jan-vandenberg/cruddiy/commit/5222763d11e79c0173119c119ec12d2b79cd6ecb

Thanks for pointing this out!
