### ISSUE TITLE
Relational table not showing the value correctly 

### ISSUE THREAD

**Issue by AndiK001** [jan-vandenberg/cruddiy#51]
Hi , Thank you for the code really  helped me  speed up the process but I tried generating the app using my two tables ( payment & Payment_status)  , but keep getting wrong value for my foreign key 
 
when I try to add a payment record the status field is showing the ID value from the reference table instead of showing the status text  like paid or canceled .. instead its showing 1 , 2 ... 

but on the display page its showing values properly  but not in create record page  !? 

please see the below setup 

payment table:
```
CREATE TABLE payments(
    ID int NOT NULL,
    student name varchar(255) NOT NULL,
    title varchar(255),
    details varchar(255),
    Status varchar(255),
    PRIMARY KEY (ID)
    INDEX KEY (STATUS)
FOREIGN KEY (STATUS) REFERENCES PAYMENT_STATUS(STATUS)
); 
```
and for the payment_status table I've got the below 
`
CREATE TABLE payments(
    ID int NOT NULL,
    status varchar(255),
    PRIMARY KEY (ID)
    INDEX KEY (STATUS)
); 
`

**Comment by jan-vandenberg** [comment]
Just a quick question are you on the latest Github commit? There was a bug that tables with only two (2) columns were not displayed properly. This is fixed in the latest commit: but that commit does not have a release yet.

**Comment by AndiK001** [comment]
I have downloaded the application from the GitHub link .. I'm not sure where to get the latest version

**Comment by jan-vandenberg** [comment]
I just created a new release, try this one: https://github.com/jan-vandenberg/cruddiy/releases/tag/v3.3
