### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by AAGRusso** [jan-vandenberg/cruddiy#54]
Hi, I just found this project and I liked it.
I am using it for a non-profit association in Spain.
I am adapting the code to their needs and I have found a problem with the pagination when using https, I have found that when generating $protocol:

$protocol=strpos(strtolower($_SERVER['SERVER_PROTOCOL']),'https') === FALSE ? 'http' : 'https';

But $_SERVER['SERVER_PROTOCOL'] = "HTTP 1.1", so it always returns http.
I have changed that line to:

$protocol=($_SERVER['HTTPS'] == "on" ? "https" : "http");

and now it seems to work correctly.

Translated with www.DeepL.com/Translator (free version)

**Comment by jan-vandenberg** [comment]
Thanks for pointing this out! Fixed in 
- https://github.com/jan-vandenberg/cruddiy/releases/tag/v3.4
- https://github.com/jan-vandenberg/cruddiy/commit/22dd22df3c2897186b0407fbd0c9983806f4b95b
