### ISSUE TITLE
No relations error and fix

### ISSUE THREAD

**Issue by apmuthu** [jan-vandenberg/cruddiy#6]
When we choose a database with **no relations** between it's tables, we get an error in line 129 of `relations.php` where `$row` is an invalid argument for the `foreach` construct. The fix is attached.
[relations.php.txt](https://github.com/jan-vandenberg/cruddiy/files/5815053/relations.php.txt)

**Comment by jan-vandenberg** [comment]
Thanks! I supplied the patch here: https://github.com/jan-vandenberg/cruddiy/commit/5fe8b347afc654bf1df8f55a2182589dba0d3a9b
