### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by liahsuum** [jan-vandenberg/cruddiy#60]
Hello:
I found your project and I like it. But, the same has 2 errors and I like your answer.
When display the information:
Notice: Undefined index: HTTPS in C:\xampp\htdocs\CRUD_DIY\app\autores-index.php on line 51
When search:
ERROR: Could not able to execute SELECT * FROM materias WHERE CONCAT_WS (descriptores) LIKE '%historia%' ORDER BY id desc LIMIT 0, 10. Incorrect parameter count in the call to native function 'CONCAT_WS'
Thanks!

**Comment by jan-vandenberg** [comment]
I think this indicate that 'descriptores' is not being passed to the query, so the query fails.

Either a typo or an empty field.

**Comment by liahsuum** [comment]
This is the error:
[image: image.png]
Muchas gracias por la atención prestada, responder a este correo y mantener
el contacto, con deferencia,

Thank you very much for the attention given, respond to this email and
maintain contact, with deference,

*LUIS M. PEÑA F., MBI*
*_____________________________________*
Quien le escribe es:
- Lic. en Lenguas Modernas mención Inglés, UASD.
- Lic. en Educación mención Bibliotecología, UASD.
- Magíster en Bibliotecología y Ciencia de la Información, PUCMM.
- Bibliotecario de los Procesos Técnicos en la Biblioteca Pedro Mir, UASD.
- Encargado del Centro de Documentación del Servicio Geológico Nacional
- Tiene especialidad en Lingüística Aplicada.
- Tiene diplomado en Archivística
- Tutor virtual graduado del INFOTEP
- Facilitador de la Formación docente graduado del INFOTEP
- Técnico en Informática y programación
*_______________________________________*
*Cel.:  829 383 1768 *
*Ofic.(DOCU-SGN): 809 732 0363 EXT. 37*
*Ofic. (Biblioteca Pedro Mir): 809 535 8273 ext. 8012*
*BLOGs: http://bibliotecahoy.blogspot.com/
<http://bibliotecahoy.blogspot.com/>*
*              http://bibliotecologiacienciadelainformacion.blogspot.com/
<http://bibliotecologiacienciadelainformacion.blogspot.com/>*

**Comment by liahsuum** [comment]
This error is when search:
[image: image.png]
Muchas gracias por la atención prestada, responder a este correo y mantener
el contacto, con deferencia,

Thank you very much for the attention given, respond to this email and
maintain contact, with deference,

*LUIS M. PEÑA F., MBI*
*_____________________________________*
Quien le escribe es:
- Lic. en Lenguas Modernas mención Inglés, UASD.
- Lic. en Educación mención Bibliotecología, UASD.
- Magíster en Bibliotecología y Ciencia de la Información, PUCMM.
- Bibliotecario de los Procesos Técnicos en la Biblioteca Pedro Mir, UASD.
- Encargado del Centro de Documentación del Servicio Geológico Nacional
- Tiene especialidad en Lingüística Aplicada.
- Tiene diplomado en Archivística
- Tutor virtual graduado del INFOTEP
- Facilitador de la Formación docente graduado del INFOTEP
- Técnico en Informática y programación
*_______________________________________*
*Cel.:  829 383 1768 *
*Ofic.(DOCU-SGN): 809 732 0363 EXT. 37*
*Ofic. (Biblioteca Pedro Mir): 809 535 8273 ext. 8012*
*BLOGs: http://bibliotecahoy.blogspot.com/
<http://bibliotecahoy.blogspot.com/>*
*              http://bibliotecologiacienciadelainformacion.blogspot.com/
<http://bibliotecologiacienciadelainformacion.blogspot.com/>*

**Comment by yvaha** [comment]
> I think this indicate that 'descriptores' is not being passed to the query, so the query fails.
> 
> Either a typo or an empty field.

Nope, the error is in the use of the CONCAT_WS function. It requires at least two parameters to function correctly. Should be replaced by the CONCAT() function or by always adding an empty string at the start of the end, so that it will work when there is only one significant column in the table. Then the result should be CONCAT_WS(**""**, field_in_the_database)

**Comment by jan-vandenberg** [comment]
The main solution should be better error handling. Feel free to send a PR!

**Comment by LevitateHigh** [comment]
I tried CONCAT_WS("", field_in_the_database), it gives same error in some other line ... problem must be some where else... @jan-vandenberg any fix ?

**Comment by jan-vandenberg** [comment]
Is there a test database I can use?

The error is mainly this:  Unknown column 'time.' in 'group statement'

The time column does not exist (or is not available)?

**Comment by LevitateHigh** [comment]
I found the issue, I was using  sql 5.6 and the function you used of $row[''] calling the index only works with sql 8, so this latest code is working fine with php 8.2 + mysql8 .. thanks @jan-vandenberg

**Comment by jan-vandenberg** [comment]
Great!
