### ISSUE TITLE
MyISAM does not support Foreign Keys

### ISSUE THREAD

**Issue by apmuthu** [jan-vandenberg/cruddiy#7]
We need a check to see if the Foreign Key constraints have been made in the table or merely stored in the session for generation purposes. MyISAM tables do not support Foreign Keys and hence the cascades would need to be in code.

**Comment by jan-vandenberg** [comment]
I think I understand what you mean. 
However I don't use MyISAM anymore (InnoDB is better) so I will probably not work on this. But feel free to work on it if you really need this.

**Comment by apmuthu** [comment]
Then atleast mark this fact in the readme.

**Comment by jan-vandenberg** [comment]
Good point! Will do.
