### ISSUE TITLE
PHP minimum version is 8.1

### ISSUE THREAD

**Issue by DebugBill** [jan-vandenberg/cruddiy#83]
Hi,

You are using the execute method with parameters to pass variables in a prepared statement rather than the "bindparam" way. According to the documentation this only appeared in PHP 8.1 and indeed it failed on my PHP 7.4 install.

Please update the documentation file as it says "PHP 7+".

Thanks

**Comment by jan-vandenberg** [comment]
Done thanks for pointing this out.
